import type { Venue } from "./types.ts";

/**
 * Real Ithaca restaurants used to seed Nessie merchants.
 *
 * Coordinates are approximate storefront positions; check each one in Google
 * Maps before the demo. Phone numbers are deliberately blank: in demo mode the
 * agent dials DEMO_HOST_PHONE (a teammate) so a real restaurant never gets a
 * test call. Fill them in only when you mean to call the real venue.
 */
export const ITHACA_VENUES: Venue[] = [
  {
    id: "ctb",
    name: "Collegetown Bagels",
    cuisine: "bagels and sandwiches",
    neighborhood: "Collegetown",
    address: "415 College Ave, Ithaca, NY 14850",
    location: { lat: 42.4421, lng: -76.48533 },
    phone: "",
    priceLevel: 1,
    typicalSpend: 11,
    bookingMethod: "walk-in",
    hours: { open: "07:00", close: "22:00" },
    serves: ["breakfast", "lunch", "dinner", "coffee"],
  },
  {
    id: "sangam",
    name: "Sangam Indian Cuisine",
    cuisine: "Indian",
    neighborhood: "Collegetown",
    address: "424 Eddy St, Ithaca, NY 14850",
    location: { lat: 42.44195, lng: -76.4859 },
    phone: "",
    priceLevel: 2,
    typicalSpend: 14,
    bookingMethod: "phone",
    hours: { open: "11:30", close: "21:30" },
    serves: ["lunch", "dinner"],
  },
  {
    id: "aladdins",
    name: "Aladdin's Natural Eatery",
    cuisine: "Mediterranean",
    neighborhood: "Collegetown",
    address: "100 Dryden Rd, Ithaca, NY 14850",
    location: { lat: 42.4421, lng: -76.4846 },
    phone: "",
    priceLevel: 2,
    typicalSpend: 15,
    bookingMethod: "phone",
    hours: { open: "11:00", close: "22:00" },
    serves: ["lunch", "dinner"],
  },
  {
    id: "taste-of-thai",
    name: "Taste of Thai Express",
    cuisine: "Thai",
    neighborhood: "Collegetown",
    address: "209 Dryden Rd, Ithaca, NY 14850",
    location: { lat: 42.44125, lng: -76.4837 },
    phone: "",
    priceLevel: 1,
    typicalSpend: 13,
    bookingMethod: "walk-in",
    hours: { open: "11:00", close: "21:30" },
    serves: ["lunch", "dinner"],
  },
  {
    id: "mama-teresa",
    name: "Mama Teresa Pizzeria",
    cuisine: "pizza",
    neighborhood: "Collegetown",
    address: "109 Dryden Rd, Ithaca, NY 14850",
    location: { lat: 42.44195, lng: -76.48425 },
    phone: "",
    priceLevel: 1,
    typicalSpend: 10,
    bookingMethod: "walk-in",
    hours: { open: "11:00", close: "02:00" },
    serves: ["lunch", "dinner"],
  },
  {
    id: "rulloffs",
    name: "Rulloff's",
    cuisine: "American pub",
    neighborhood: "Collegetown",
    address: "411 College Ave, Ithaca, NY 14850",
    location: { lat: 42.44225, lng: -76.48528 },
    phone: "",
    priceLevel: 3,
    typicalSpend: 24,
    bookingMethod: "phone",
    hours: { open: "11:00", close: "01:00" },
    serves: ["lunch", "dinner", "drinks"],
  },
  {
    id: "the-nines",
    name: "The Nines",
    cuisine: "pizza and bar",
    neighborhood: "Collegetown",
    address: "311 College Ave, Ithaca, NY 14850",
    location: { lat: 42.4433, lng: -76.4855 },
    phone: "",
    priceLevel: 2,
    typicalSpend: 16,
    bookingMethod: "phone",
    hours: { open: "16:00", close: "01:00" },
    serves: ["dinner", "drinks"],
  },
  {
    id: "gola",
    name: "Gola Osteria",
    cuisine: "Italian",
    neighborhood: "Collegetown",
    address: "115 S Quarry St, Ithaca, NY 14850",
    location: { lat: 42.4393, lng: -76.4863 },
    phone: "",
    priceLevel: 4,
    typicalSpend: 48,
    bookingMethod: "phone",
    hours: { open: "17:00", close: "22:00" },
    serves: ["dinner"],
  },
  {
    id: "moosewood",
    name: "Moosewood Restaurant",
    cuisine: "vegetarian",
    neighborhood: "Downtown",
    address: "215 N Cayuga St, Ithaca, NY 14850",
    location: { lat: 42.4406, lng: -76.4984 },
    phone: "",
    priceLevel: 3,
    typicalSpend: 22,
    bookingMethod: "phone",
    hours: { open: "11:30", close: "20:30" },
    serves: ["lunch", "dinner"],
  },
  {
    id: "viva",
    name: "Viva Taqueria & Cantina",
    cuisine: "Mexican",
    neighborhood: "The Commons",
    address: "101 N Aurora St, Ithaca, NY 14850",
    location: { lat: 42.43965, lng: -76.4958 },
    phone: "",
    priceLevel: 1,
    typicalSpend: 13,
    bookingMethod: "walk-in",
    hours: { open: "11:00", close: "22:00" },
    serves: ["lunch", "dinner", "drinks"],
  },
  {
    id: "simeons",
    name: "Simeon's on the Commons",
    cuisine: "American",
    neighborhood: "The Commons",
    address: "224 E State St, Ithaca, NY 14850",
    location: { lat: 42.43914, lng: -76.4959 },
    phone: "",
    priceLevel: 3,
    typicalSpend: 26,
    bookingMethod: "phone",
    hours: { open: "11:00", close: "23:00" },
    serves: ["lunch", "dinner", "drinks"],
  },
  {
    id: "lev",
    name: "Lev Kitchen",
    cuisine: "Mediterranean bowls",
    neighborhood: "The Commons",
    address: "106 E State St, Ithaca, NY 14850",
    location: { lat: 42.4393, lng: -76.4977 },
    phone: "",
    priceLevel: 1,
    typicalSpend: 13,
    bookingMethod: "walk-in",
    hours: { open: "11:00", close: "21:00" },
    serves: ["lunch", "dinner"],
  },
  {
    id: "ale-house",
    name: "Ithaca Ale House",
    cuisine: "pub food",
    neighborhood: "The Commons",
    address: "111 N Aurora St, Ithaca, NY 14850",
    location: { lat: 42.43985, lng: -76.49575 },
    phone: "",
    priceLevel: 2,
    typicalSpend: 15,
    bookingMethod: "phone",
    hours: { open: "11:30", close: "00:00" },
    serves: ["lunch", "dinner", "drinks"],
  },
  {
    id: "coltivare",
    name: "Coltivare",
    cuisine: "farm to table",
    neighborhood: "Downtown",
    address: "235 S Cayuga St, Ithaca, NY 14850",
    location: { lat: 42.4373, lng: -76.4991 },
    phone: "",
    priceLevel: 3,
    typicalSpend: 32,
    bookingMethod: "phone",
    hours: { open: "16:00", close: "22:00" },
    serves: ["dinner", "drinks"],
  },
  {
    id: "saigon-kitchen",
    name: "Saigon Kitchen",
    cuisine: "Vietnamese",
    neighborhood: "Downtown",
    address: "526 W State St, Ithaca, NY 14850",
    location: { lat: 42.4398, lng: -76.5068 },
    phone: "",
    priceLevel: 2,
    typicalSpend: 14,
    bookingMethod: "phone",
    hours: { open: "11:00", close: "21:30" },
    serves: ["lunch", "dinner"],
  },
];

export function priceRange(level: Venue["priceLevel"]): string {
  return ["", "under $12", "$12–20", "$20–35", "$35+"][level]!;
}
